config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  get 'property_type' => 'orders#property_type', as: 'property_type'
  get 'about_property' => 'orders#about_property', as: 'about_property'
  get 'exterior' => 'orders#exterior', as: 'exterior'
  get 'still_photo' => 'orders#still_photo', as: 'still_photo'
  get 'floor_plan' => 'orders#floor_plan', as: 'floor_plan'
  get 'custome_domain' => 'orders#custome_domain', as: 'custome_domain'
  get 'review' => 'orders#review', as: 'review'
  root 'orders#property_type'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :property_type
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :orders
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order

  def property_type
    @property_types = PropertyType.all
    @property_type_id = (@order.property_type == nil) ? 1 : @order.property_type.id

    respond_to do |format|
      format.html
      format.js
    end
  end

  def about_property
    if params[:id]
      @order.property_type_id = params[:id]
      @order.save
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def exterior
    respond_to do |format|
      format.html
      format.js
    end
  end

  def still_photo
    @photos = Photo.all
    @photo_id = (@order.photo == nil) ? 1 : @order.photo.id
    if params[:id]
      @order.exterior_tour = params[:id]
      @order.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def floor_plan
    @photo_id = (@order.photo == nil) ? 1 : @order.photo.id
    if params[:id]
      @order.photo_id = params[:id]
      @order.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def custome_domain
    if params[:id]
      @order.floor_plan = params[:id]
      @order.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def review
    if params[:id]
      @order.custome_domain = params[:id]
      @order.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to exterior_path
  end

  private

    def set_order
      @order = Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
      @order = Order.create
      session[:order_id] = @order.id
    end

    def order_params
      params.require(:order).permit(:property_type, :property_address, :sqft,
                                    :number_of_units, :exterior_tour,
                                    :floor_plan, :still_photo, :custome_domain,
                                    :detach_space)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def active_property_type property_type_id
    return 'active' if @order.property_type == nil && property_type_id == 1
    (@order.property_type == nil || @order.property_type.id != property_type_id) ? '' : 'active'
  end

  def active_still_photo photo_id
    return 'active' if @order.photo == nil && photo_id == 1
    (@order.photo == nil || @order.photo.id != photo_id) ? '' : 'active'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Walkintour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">

    <%= render 'shared/header' %>

    <div id="main-fon">

      <%= yield %>

      <div class="clear"></div>
      <div class="content">
        <div class="body-left">
          <h1>Basic Package starting at <span>$200</span></h1>
          <p>Our most affordable package will have your buyers virtually stepping through the front door and perusing the rooms of your listing via our advanced 3D WalkIn Tour. Your beautiful website will be ready to link to an MLS database and provide visitors the best remote tour experience on the market. Give buyers access to a 24/7 open house no matter where they are.
          </p>
          <p>Order our Basic Package and you'll discover the persuasive power of the WalkIn solution.
          </p>
          <%= image_tag 'video.png', id: 'video' %>
          <h1>*Additional Spaces</h1>
          <p>Extra charges apply to space in addition to main structure square footage, such as an attic or basement.
          </p>
          <p>Our scanning technology requires a second 3D model to be created for space that is not interiorly connected to the main space, or that has limited access. Common scenarios include:
          </p>
          <ol>
            <li>Detached pool house.</li>
            <li>Detached workshop.</li>
            <li>Basement/in-law unit not connected by an interior staircase.</li>
            <li>Townhouse with two units, not connected by an interior door.</li>
            <li>Basement that is only accessible by trap door, or attic that is only accessible by ladder.</li>
          </ol>
        </div>
        <div class="body-right">
          <h1>Basic Package includes:</h1>
          <p>3D WalkIn Tour<br/>
            Single Property Website<br/>
            (see samples on our pricing page)
          </p>
          <h1>Appointment option</h1>
          <p>Due to high demand, our appointments are generally 3 days out from the date you place your oder. Enter a desirable date and time in the text field, and we'll work with your schedule.
          </p>
          <h1>Combo lockbox option</h1>
          <p>If your property is vacant and camera ready, and there is a combo lockbox on-site, our techician will scan your property the next day. Using this option, the exact time of the scan is not guaranteed, but will be between 8am and sunset. Enter the lockbox combo and location in the text field.
          </p>
        </div>
      </div>

      <div class="clear"></div>

    </div>

    <%= render 'shared/footer' %>

  </div>
</body>
</html>

app/views/orders/_about_property_remote.html.erb
<div id="walkintour">
  <%= image_tag 'walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag '3d-image.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Tell us more about Your Property
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<%= form_for @order, remote: true do |f| %>

  <div id="tab-types">
    <div class="control-label">
      <%= f.label :property_address %>
    </div>
    <div>
      <%= f.text_area :property_address, autofocus: true,
                       placeholder: 'Property Address, City, State, Zip Code' %>
    </div>

    <div class="control-label padding-top-label">
      <%= f.label :sqft %>
    </div>
    <div class="form-control">
      <%= f.text_field :sqft, size: 22, placeholder: 'Property Sqft' %>
    </div>

    <div class="control-label padding-top-label">
      Access
    </div>
    <div class="pick-appointment">
      <%= link_to 'Click to Pick Appointment Preferences', '#' %>
    </div>

    <div class="control-label padding-top-label">
      Number of Units
    </div>
    <div class="numbers">
      <div class="minus" id="number-of-units-minus">-</div>
      <div><%= f.text_field :number_of_units, readonly: true, id: "number" %></div>
      <div class="plus" id="number-of-units-plus">+</div>
    </div>

    <div class="control-label padding-top-label clear-left">
      Additional Detach Space <span>like Attic/Basement&amp;Buildings</span>
    </div>

    <div class="numbers">
      <div class="minus" id="detach-space-minus">-</div>
      <div><%= f.text_field :detach_space, readonly: true, id: "detach-space" %></div>
      <div class="plus" id="detach-space-plus">+</div>
    </div>

  </div>

  <div id="bellow-options">

    <div id="bellow-previous">
      <%= link_to property_type_path, remote: true do %>
        <span id="previous">&lt;</span>
        PREVIOUS
      <% end %>
    </div>

    <div id="bellow-slider">
       <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-green.png' %>
    </div>

    <div id="bellow-next">
      <%= f.submit "NEXT >", class: 'submit-next', remote: true %>
    </div>

  </div>

<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $(".minus").click(function() {
      if($(this).attr("id") == "number-of-units-minus") {
        var i = parseInt($("#number").val());
        i = (--i < 0)? 0 : i;
        $("#number").val(i);
      }
      else {
        var i = parseInt($("#detach-space").val());
        i = (--i < 0)? 0 : i;
        $("#detach-space").val(i);
      }
    });

    $(".plus").click(function() {
      if($(this).attr("id") == "number-of-units-plus") {
        var i = parseInt($("#number").val());
        i = (++i < 0)? 0 : i;
        $("#number").val(i);
      }
      else {
        var i = parseInt($("#detach-space").val());
        i = (++i < 0)? 0 : i;
        $("#detach-space").val(i);
      }
    });
  });
</script>

app/views/orders/_custome_domain_remote.html.erb
<div id="walkintour">
  <%= image_tag 'custome-domain-walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag 'custome-domain.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Add Custome Domain to Your Website
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">
  <div class="tab-type <%= @order.custome_domain ? '' : 'active' %>" id="false">
    <div class="type">
      No Custome Domain
    </div> 
    <div class="type-image"><%= image_tag 'type-image.png' %></div>
  </div>

  <div class="tab-type <%= @order.custome_domain ? 'active' : '' %>" id="true">
    <div class="type">
      Add Custome Domain (+19.99)
    </div> 
    <div class="type-image"><%= image_tag 'type-image.png' %></div>
  </div>
</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to floor_plan_path, remote: true do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
       <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-gray.png' %>
       <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-green.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to review_path(id: @order.custome_domain), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>
</div>

<div class="clear"></div>
<div class="exterior-tour-plus">
  <%= image_tag 'custome-domain-plus.png' %>
</div>
<div class="exterior-tour-plus-fon"></div>
<div class="paragraph">- Included with every order, our attractive website templatetakes only minutes to modify
</div>
<div class="paragraph">- Add a custom domain to make your single property  websiteeas to remember
</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/review?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/_exterior_remote.html.erb
<div id="walkintour">
  <%= image_tag 'exterior-tour-walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag 'exterior-tour.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Add Exterior WALKINTOUR
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">
  <div class="tab-type <%= @order.exterior_tour ? '' : 'active' %>" id="false">
    <div class="type">
      No Exterior WALKINTOUR
    </div> 
    <div class="type-image"><%= image_tag 'type-image.png' %></div>
  </div>

  <div class="tab-type <%= @order.exterior_tour ? 'active' : '' %>" id="true">
    <div class="type">
      Add Exterior WALKINTOUR (+100)
    </div> 
    <div class="type-image"><%= image_tag 'type-image.png' %></div>
  </div>
</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to about_property_path, remote: true do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
      <%= image_tag 'sl-green.png' %> <%= image_tag 'sl-gray.png' %>
      <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-gray.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to still_photo_path(id: @order.exterior_tour), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>
</div>

<div class="clear"></div>
<div class="exterior-tour-plus">
  <%= image_tag 'exterior-tour-plus.png' %>
</div>
<div class="exterior-tour-plus-fon"></div>
<div class="paragraph">- We have revolutionaized the visualization of outdoor space so that you acn feature the exterior selling points of your 3D WALKINTOUR. Give your buyers the freedom to explore the entirety of the property, experienceing the home inside and out.
</div>
<div class="paragraph">- Further distinguish our marketing strategy by adding an Exterioir WALKINTOUR to your order
</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/still_photo?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/_property_type_remote.html.erb
<div id="walkintour">
  <%= image_tag 'walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag '3d-image.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Tell us more about Your Property Type
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">

  <% @property_types.each do |property_type| %>
    <div class="tab-type <%= active_property_type property_type.id %>" id="<%= property_type.id %>">
      <div class="type">
        <%= property_type.title %>
      </div> 
      <div class="type-image"><%= image_tag 'type-image.png' %></div>
    </div>
  <% end %>

</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to '#' do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
      <%= image_tag 'sl-green.png' %> <%= image_tag 'sl-gray.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to about_property_path(id: @property_type_id), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>

</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/about_property?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/_still_photo_remote.html.erb
<div id="walkintour">
  <%= image_tag 'exterior-tour-walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag 'still-photo.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Add Still Photo
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">

  <% @photos.each do |photo| %>
    <div class="tab-type <%= active_still_photo photo.id %>" id="<%= photo.id %>">
      <div class="type<%= photo.id != 1 ? '-rows' : '' %>">
        <%= photo.title %>
      </div> 
      <div class="type-image"><%= image_tag 'type-image.png' %></div>
    </div>
  <% end %>
</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to exterior_path, remote: true do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
      <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-green.png' %>
      <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-gray.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to floor_plan_path(id: @photo_id), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>
</div>

<div class="clear"></div>
<div class="exterior-tour-plus">
  <%= image_tag 'still-photo-plus.png' %>
</div>
<div class="exterior-tour-plus-fon"></div>
<div class="paragraph">- we can create traditional home layouts more quickly and affordably than ever before.
</div>
<div class="paragraph">- Hand out our new-construction style flor plan featuring your branding to make a lasting impressing on your buyers and sellers (required 2-3 business days to create)
</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/floor_plan?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/about_property.html.erb
<div id="main">
  <%= render 'about_property_remote' %>
</div>

app/views/orders/about_property.js.erb
$('#main').html('<%= escape_javascript render(partial: "about_property_remote") %>');

app/views/orders/custome_domain.js.erb
$('#main').html('<%= escape_javascript render(partial: "custome_domain_remote") %>');

app/views/orders/exterior.js.erb
$('#main').html('<%= escape_javascript render(partial: "exterior_remote") %>');

app/views/orders/property_type.html.erb
<div id="main">
  <%= render 'property_type_remote' %>
</div>

app/views/orders/property_type.js.erb
$('#main').html('<%= escape_javascript render(partial: "property_type_remote") %>');

app/views/orders/review.js.erb
$('#main').html('<%= escape_javascript render(partial: "review_remote") %>');

app/views/orders/still_photo.html.erb
<div id="main">
  <%= render 'still_photo_remote' %>
</div>

app/views/orders/still_photo.js.erb
$('#main').html('<%= escape_javascript render(partial: "still_photo_remote") %>');

app/views/shared/_configuration_header.html.erb
<div id="configuration-header">
  <table>
    <thead>
      <tr>
        <th class="line">Your configuration</th>
        <th class="line">Save</th>
        <th>Competitors</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="line">$599.00</td>
        <td class="line">$62.00</td>
        <td>$1000.00</td>
      </tr>
      <tr>
        <td class="introductory">Introductory Offer</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div id="walk-future">
    <%= image_tag 'walk-future.png' %>
  </div>

  <div id="map">
    <%= image_tag 'map.png' %>
  </div>
  <div class="block">
    <h2>WALKINTOUR OFFICE</h2>
    <p>3118 Diablo Ave, Hayward,<br/> CA, 94545</p>
  </div>
  <div class="block">
    <h2>MORE PAGES</h2>
    <ul>
      <li><%= link_to 'About', '#' %></li>
      <li><%= link_to 'Help', '#' %></li>
      <li><%= link_to 'Tutorial', '#' %></li>
      <li><%= link_to 'Blog', '#' %></li>
      <li><%= link_to 'Press', '#' %></li>
      <li><%= link_to 'Terms & Privacy', '#' %></li>
    </ul>
  </div>
  <div class="block">
    <h2>FOLLOW US</h2>
    <p>
      <%= link_to '#', class: 'follow-us' do %>
        <%= image_tag 'facebook.png', class: 'follow-us' %>
      <% end %>
      <%= link_to '#', class: 'follow-us' do %>
        <%= image_tag 'twitter.png', class: 'follow-us' %>
      <% end %>

      <%= link_to '#', class: 'follow-us' do %>
        <%= image_tag 'instagram.png', class: 'follow-us' %>
      <% end %>
      <%= link_to '#', class: 'follow-us' do %>
        <%= image_tag 'youtube.png', class: 'follow-us' %>
      <% end %>
      <%= link_to '#', class: 'follow-us' do %>
        <%= image_tag 'google.png', class: 'follow-us' %>
      <% end %>
    </p>
    <p>
      <%= link_to '#', class: 'follow-us' do %>
        <%= image_tag 'lg-1.png', class: 'follow-us' %>
      <% end %>
      <%= link_to '#', class: 'follow-us' do %>
        <%= image_tag 'lg-2.png', class: 'follow-us' %>
      <% end %>
    </p>
  </div>

  <div class="clear"></div>
  <div id="copyright">
    Copyright &copy; 2015 WalkIn Photography, Inc.
  </div>
  <div id="partnership">
    PARTNERSHIP OPPORTUNITIES
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <%= link_to root_path do %>
    <%= image_tag 'logo.png', id: 'logo' %>
  <% end %>
  <nav>
    <ul class="topmenu">
      <li><%= link_to 'Home', '#' %></li>
      <li><%= link_to 'Pricing', '#' %></li>
      <li><%= link_to 'Why us', '#' %></li>
      <li><%= link_to 'Contact us', '#', id: 'contact-us' %></li>
    </ul>

    <ul class="topmenu topmenu-right">
      <li><%= link_to 'Order Now','#', class: 'active' %></li>
      <li><%= link_to 'Sign In','#', id: 'sign-in' %></li>
    </ul>
  </nav>
</header>
<div class="clear"></div>